sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GRl77FyF1YKCyEutzfPKWueZ/CpDFBpx7JWqeFmXdDaBLiwXljPW+5ETmtIOsxJPUp4Uday1At7bop8Zz064oJxQwYDHfNkPUCAQMP7Zi6ZIdxOv2jmN302ZGFNlQKqCF8Slp/EMSKgnoGYtQlgwneukz4c0d5fwj+z4ll9d05UDiMkzcU4/kJAWHnE3zT8YJ8onrlkk0SCcdKkCs7cRiarbHsse7nPSuFPcdt33ARN5a4Ayj+4OyU/S59x54KB/ZZIduz3YSAqll437MSQHf3TkCpNxp7PxhUu+/JxkWNx1e3uk4/ELskznEaAevwPCsxKUqNRN7ZxGn02o4NntAqCStB+2VCWKgQ1deA48xXDHWwvm5B040y0H/AxHx0vDK0Dd3nWy8GSq6NvK//lJmul8EqD+rCV2EWXjeXWflqihKmigICBzuoRRRMn69aROH9BXbO7R38OWPKAOOsraNvadlRn4OZE6u5UTqJxjeLErWfIY9u27LOZA+a8qlQpNkidjcLqlDfJQMKJW4eZ8hZ6VwmzVXhf1VeEm2ueUg0RNHFS7pW77Ia7WwVpF6sJ2m/hWjTVs7tN6Pgomh3cQOpsUsLJJ+wFoeGVkfrx+KEWc5PebRTRbAcLjgrDQMUTdj8dhBTiFqvKWziMpHfHF9CXGflkiMxr/EKSFa1DoxtI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Battle-of-the-Strong-A-Romance-of-Two-Kingdoms-Volume-1_6230
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy